### ISSUE TITLE
Error using example data

### ISSUE THREAD

**Issue by hdetering** [morrislab/pairtree#1] opened 2020-11-25 09:41 UTC
Hi *,

when running Pairtree with the example data, it produced the following error:

```
(pairtree)[uvibehde@c6601 results]$ ${CONDA_DEFAULT_ENV}/bin/python3 ../../bin/pairtree --params ../example.params.json ../example.ssm example.results.npz
Computing supervariant relations: 100%|██████████████████████████████████| 6/6 [00:00<00:00, 25.39pair/s]
Sampling trees:   2%|▉                                           | 1556/72000 [00:41<11:25, 102.83tree/s]Exception occurred in child process: arrays used as indices must be of integer (or boolean) type
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/mnt/netapp1/posadalab/APPS/CommonCondaEnvironments/pairtree/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "../../bin/../lib/tree_sampler.py", line 451, in _run_chain
    samps = [_init_chain(seed, data_logmutrel, __calc_phi, __calc_llh_phi)]
  File "../../bin/../lib/tree_sampler.py", line 329, in _init_chain
    init_adj = _init_cluster_adj_mutrels(data_logmutrel)
  File "../../bin/../lib/tree_sampler.py", line 96, in _init_cluster_adj_mutrels
    truncated_logmutrel = mutrel.remove_variants_by_vidx(data_logmutrel, others - 1)
  File "../../bin/../lib/mutrel.py", line 19, in remove_variants_by_vidx
    rels = util.remove_rowcol(mrel.rels, vidxs),
  File "../../bin/../lib/util.py", line 89, in remove_rowcol
    arr = np.delete(arr, indices, axis=axis)
  File "<__array_function__ internals>", line 5, in delete
  File "/mnt/netapp1/posadalab/APPS/CommonCondaEnvironments/pairtree/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: arrays used as indices must be of integer (or boolean) type
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../../bin/pairtree", line 169, in <module>
    main()
  File "../../bin/pairtree", line 130, in main
    adjm, phi, llh, accept_rate = tree_sampler.sample_trees(
  File "../../bin/../lib/tree_sampler.py", line 635, in sample_trees
    raise exception
IndexError: arrays used as indices must be of integer (or boolean) type
Exception ignored in: <function tqdm.__del__ at 0x7f2b2b0d3ee0>
Traceback (most recent call last):
  File "/mnt/netapp1/posadalab/APPS/CommonCondaEnvironments/pairtree/lib/python3.8/site-packages/tqdm/std.py", line 1128, in __del__
  File "/mnt/netapp1/posadalab/APPS/CommonCondaEnvironments/pairtree/lib/python3.8/site-packages/tqdm/std.py", line 1341, in close
  File "/mnt/netapp1/posadalab/APPS/CommonCondaEnvironments/pairtree/lib/python3.8/site-packages/tqdm/std.py", line 1520, in display
  File "/mnt/netapp1/posadalab/APPS/CommonCondaEnvironments/pairtree/lib/python3.8/site-packages/tqdm/std.py", line 1131, in __repr__
  File "/mnt/netapp1/posadalab/APPS/CommonCondaEnvironments/pairtree/lib/python3.8/site-packages/tqdm/std.py", line 1481, in format_dict
TypeError: cannot unpack non-iterable NoneType object
```

To me it's not obvious what exactly may have caused the problem.
Have you seen this before?

Best,
Harry

**Comment by jwintersinger** [comment] 2020-11-26 00:38
Hi Harry,

Thank you for reporting this! The issue seemed to arise because of a slight change in recent NumPy versions. I was able to reproduce the problem after upgrading from NumPy 1.18.1 to 1.19.2.

The issue should be fixed now if you pull the latest commits from master and try again. Please let me know if you run into any other problems!

**Comment by hdetering** [comment] 2020-11-26 11:23
Dear Jeff,

thank you for the quick reply - indeed your changes fixed the problem!

Just FYI, these are the versions of the packages I used:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.10.14                    0  
certifi                   2020.11.8        py38h06a4308_0  
intel-openmp              2020.2                      254  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libllvm10                 10.0.1               hbcb73fb_5  
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.34.0           py38h269e1b5_4  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
numba                     0.51.2           py38h0573a6f_1  
numpy                     1.19.2           py38h54aff64_0  
numpy-base                1.19.2           py38hfa32c7d_0  
openssl                   1.1.1h               h7b6447c_0  
pip                       20.2.4           py38h06a4308_0  
python                    3.8.5                h7579374_1  
readline                  8.0                  h7b6447c_0  
scipy                     1.5.2            py38h0b6359f_0  
setuptools                50.3.1           py38h06a4308_1  
six                       1.15.0           py38h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
tk                        8.6.10               hbc83047_0  
tqdm                      4.51.0             pyhd3eb1b0_0  
wheel                     0.35.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3 
```

**Closed** 2020-11-26 11:23 UTC

**Comment by hdetering** [comment] 2020-11-26 11:40
Thanks for updating the README as well.

You could also include `plotly` and `scikit-learn` as a dependencies, as `plottree` is using them. At least I had to install them (in addition to `colorlover`) to successfully run `plottree`.

**Comment by jwintersinger** [comment] 2020-11-26 17:54
Thanks for pointing out the missing dependencies, @hdetering! I added them to the README.
